FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

# Install GitLab Runner
RUN apt-get update && apt-get install -y curl ca-certificates gnupg && \
    curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | bash && \
    apt-get install -y gitlab-runner && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Create unprivileged user
RUN useradd --comment "GitLab Runner" --create-home gitlab-runner --shell /bin/bash
USER gitlab-runner
WORKDIR /home/gitlab-runner

# Port required by AdaLab (unused)
EXPOSE 8888

ENTRYPOINT ["bash", "-c"]
CMD ["gitlab-runner register --non-interactive --url ${CI_SERVER_URL} --registration-token ${REGISTRATION_TOKEN} --executor ${RUNNER_EXECUTOR:-shell} --description ${RUNNER_NAME} --tag-list ${RUNNER_TAGS} && gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner"]
